# Generated by Django 4.1.4 on 2022-12-18 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_name", models.CharField(max_length=250)),
                ("emp_email", models.EmailField(max_length=254)),
                ("emp_phonenumber", models.CharField(max_length=250)),
                ("emp_role", models.CharField(max_length=250)),
                ("emp_salary", models.IntegerField()),
                (
                    "emp_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
